// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1WG_ZNR9VdPl-OtrMQAZ1VFxFo8Gw-mQ',
    appId: '1:862463876191:android:87044b446129101e910fea',
    messagingSenderId: '862463876191',
    projectId: 'erp-system-9a5fd',
    storageBucket: 'erp-system-9a5fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgBN11w8Lu1JH_BfnT-DhRTPjw-5-OAxU',
    appId: '1:862463876191:ios:96244b93be14a6fd910fea',
    messagingSenderId: '862463876191',
    projectId: 'erp-system-9a5fd',
    storageBucket: 'erp-system-9a5fd.firebasestorage.app',
    iosBundleId: 'com.deverpsystem.erpSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgBN11w8Lu1JH_BfnT-DhRTPjw-5-OAxU',
    appId: '1:862463876191:ios:96244b93be14a6fd910fea',
    messagingSenderId: '862463876191',
    projectId: 'erp-system-9a5fd',
    storageBucket: 'erp-system-9a5fd.firebasestorage.app',
    iosBundleId: 'com.deverpsystem.erpSystem',
  );
}
